"""estat_versio aprovat_per aprovat_at

Revision ID: 080e91f28f8a
Revises: 6e9aea821e4b
Create Date: 2026-04-20 15:14:11.268230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080e91f28f8a'
down_revision = '6e9aea821e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versio_fitxa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estat_versio', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aprovat_per', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('aprovat_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versio_fitxa', schema=None) as batch_op:
        batch_op.drop_column('aprovat_at')
        batch_op.drop_column('aprovat_per')
        batch_op.drop_column('estat_versio')

    # ### end Alembic commands ###
