"""seccions fitxa i camps dinamics

Revision ID: 66ccd5cae794
Revises: d0e969257f62
Create Date: 2026-04-17 16:34:46.372235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ccd5cae794'
down_revision = 'd0e969257f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seccio_fitxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camp_fitxa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seccio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_defecte', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'seccio_fitxa', ['seccio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_fitxa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('valor_defecte')
        batch_op.drop_column('seccio_id')

    op.drop_table('seccio_fitxa')
    # ### end Alembic commands ###
