"""afegir es_client observacions data_comprovacio

Revision ID: 6e9aea821e4b
Revises: 8c20b1b6d60e
Create Date: 2026-04-20 09:01:51.141987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9aea821e4b'
down_revision = '8c20b1b6d60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitxa_tecnica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_client', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('observacions', sa.Text(), nullable=True))

    with op.batch_alter_table('versio_fitxa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_comprovacio', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versio_fitxa', schema=None) as batch_op:
        batch_op.drop_column('data_comprovacio')

    with op.batch_alter_table('fitxa_tecnica', schema=None) as batch_op:
        batch_op.drop_column('observacions')
        batch_op.drop_column('es_client')

    # ### end Alembic commands ###
