"""afegir taules job_bulk i job_item per operacions massives

Revision ID: 88b8888d9e19
Revises: a3f5c8d2e1b4
Create Date: 2026-05-28 14:04:39.755426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b8888d9e19'
down_revision = 'a3f5c8d2e1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_bulk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus', sa.String(length=40), nullable=False),
    sa.Column('estat', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('items_ok', sa.Integer(), nullable=True),
    sa.Column('items_error', sa.Integer(), nullable=True),
    sa.Column('items_pendents', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('arxivat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('fitxa_id', sa.Integer(), nullable=False),
    sa.Column('desti_id', sa.Integer(), nullable=True),
    sa.Column('estat', sa.String(length=20), nullable=False),
    sa.Column('missatge_error', sa.Text(), nullable=True),
    sa.Column('executat_at', sa.DateTime(), nullable=True),
    sa.Column('intent_count', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['desti_id'], ['desti_distribucio.id'], ),
    sa.ForeignKeyConstraint(['fitxa_id'], ['fitxa_tecnica.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_bulk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.create_index('ix_job_item_estat_locked', ['estat', 'locked_at'], unique=False)
        batch_op.create_index('ix_job_item_job_estat', ['job_id', 'estat'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_item_job_id'))
        batch_op.drop_index('ix_job_item_job_estat')
        batch_op.drop_index('ix_job_item_estat_locked')

    op.drop_table('job_item')
    op.drop_table('job_bulk')
    # ### end Alembic commands ###
