"""tipus fitxa

Revision ID: 8c20b1b6d60e
Revises: 66ccd5cae794
Create Date: 2026-04-17 16:58:42.377069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c20b1b6d60e'
down_revision = '66ccd5cae794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipus_fitxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('actiu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('fitxa_tecnica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipus_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipus_fitxa', ['tipus_id'], ['id'])

    with op.batch_alter_table('seccio_fitxa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipus_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipus_fitxa', ['tipus_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seccio_fitxa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipus_id')

    with op.batch_alter_table('fitxa_tecnica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipus_id')

    op.drop_table('tipus_fitxa')
    # ### end Alembic commands ###
