"""creacio inicial

Revision ID: 9e027de134ca
Revises: 
Create Date: 2026-04-17 15:17:56.739637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e027de134ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camp_fitxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('tipus', sa.String(length=20), nullable=True),
    sa.Column('obligatori', sa.Boolean(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('opcions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitxa_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art_codi', sa.String(length=50), nullable=False),
    sa.Column('nom_producte', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('art_codi')
    )
    op.create_table('versio_fitxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fitxa_id', sa.Integer(), nullable=False),
    sa.Column('num_versio', sa.Integer(), nullable=False),
    sa.Column('descripcio_canvi', sa.Text(), nullable=False),
    sa.Column('contingut', sa.JSON(), nullable=True),
    sa.Column('fitxer_docx', sa.String(length=500), nullable=True),
    sa.Column('fitxer_pdf', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fitxa_id'], ['fitxa_tecnica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribucio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versio_id', sa.Integer(), nullable=False),
    sa.Column('desti', sa.String(length=20), nullable=False),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('intents', sa.Integer(), nullable=True),
    sa.Column('missatge_error', sa.Text(), nullable=True),
    sa.Column('executat_at', sa.DateTime(), nullable=True),
    sa.Column('executat_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['versio_id'], ['versio_fitxa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribucio')
    op.drop_table('versio_fitxa')
    op.drop_table('fitxa_tecnica')
    op.drop_table('camp_fitxa')
    # ### end Alembic commands ###
