"""usuaris i destins distribucio

Revision ID: d0e969257f62
Revises: 9e027de134ca
Create Date: 2026-04-17 15:36:24.135428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e969257f62'
down_revision = '9e027de134ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desti_distribucio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('tipus', sa.String(length=20), nullable=False),
    sa.Column('configuracio', sa.JSON(), nullable=False),
    sa.Column('patro_nom_fitxer', sa.String(length=200), nullable=False),
    sa.Column('actiu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('actiu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('distribucio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desti_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'desti_distribucio', ['desti_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribucio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('desti_id')

    op.drop_table('usuari')
    op.drop_table('desti_distribucio')
    # ### end Alembic commands ###
